# Generated by Django 5.0.6 on 2024-07-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.TextField(unique=True),
        ),
    ]
