# Generated by Django 5.0.6 on 2024-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='segment_code',
            field=models.TextField(),
        ),
    ]
