# Generated by Django 5.0.6 on 2024-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_segment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_code',
            field=models.TextField(),
        ),
    ]
